mysqldata_raw:
  image: busybox
  volumes:
   - /var/lib/mysql
  command: echo Data-only container for Mysql

mysql_raw:
  image: mysql:5.7
  volumes_from:
   - mysqldata_raw
  environment:
   MYSQL_ROOT_PASSWORD: ${MYSQL_RAW_DATA_ROOT_PASSWORD}
   MYSQL_USER: ${MYSQL_RAW_DATA_USER_NAME}
   MYSQL_DATABASE: bicing_raw
   MYSQL_PASSWORD: ${MYSQL_RAW_DATA_USER_PASSWORD}

querybicing:
  image: golang:1.5.3
  working_dir: /code
  command: bash -c "go install github.com/alexcarol/bicing-oracle && /code/bin/bicing-oracle"
  volumes:
   - .:/code/src/github.com/alexcarol/bicing-oracle
  environment:
   BICING_API_POLLING_TIME: 45
   MYSQL_RAW_DATA_NAME: bicing_raw
   MYSQL_RAW_DATA_USER: ${MYSQL_RAW_DATA_USER_NAME}
   MYSQL_RAW_DATA_PASSWORD: ${MYSQL_RAW_DATA_ROOT_PASSWORD}
   MYSQL_RAW_DATA_ADDRESS: mysql_raw:3306
   GOPATH: /code
  links:
   - mysql_raw
