# mysqldata:
#   image: busybox
#   volumes:
#    - /var/lib/mysql
#   command: echo Data-only container for Mysql
#
# mysql:
#   image: mysql:5.7
#   volumes_from:
#    - mysqldata
#   environment:
#    MYSQL_ROOT_PASSWORD: secretpassword
#    MYSQL_USER: alex
#    MYSQL_DATABASE: bicing_raw
#    MYSQL_PASSWORD: alexpassword

querybicing:
    image: golang:1.5.3
    working_dir: /code
    command: bash -c "go get github.com/go-sql-driver/mysql github.com/alexcarol/bicing-oracle/station-state/datasource && go run /code/main.go"
    volumes:
        - .:/code
    # environment:
    # links:
    #     - mysql
